[project]
name = "elektron-mcp"
version = "0.1.0"
description = "MPC to control Elektron machines (Digitakt 2, Digitone 2)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "fastmcp>=0.4.1",
 "pydantic-ai-slim[mcp]>=0.0.43",
]
