# LFO Destinations
BASE_DESTINATIONS = [
    "none",
    "FILTER: Base",
    "FILTER: Width",
    "FILTER: Env. Reset",
    "AMP: Attack Time",
    "AMP: Hold Time",
    "AMP: Decay Time",
    "AMP: Sustain Level",
    "AMP: Release Time",
    "AMP: Pan",
    "AMP: Volume",
    "FX: Delay Send",
    "FX: Reverb Send",
    "FX: Chorus Send",
    "FX: Bit Reduction",
    "FX: SRR",
    "FX: SRR Routing",
    "FX: Overdrive",
    "SYN: Data entry knob A, page 1–4",
    "SYN: Data entry knob B, page 1–4",
    "SYN: Data entry knob C, page 1–4",
    "SYN: Data entry knob D, page 1–4",
    "SYN: Data entry knob E, page 1–4",
    "SYN: Data entry knob F, page 1–4",
    "SYN: Data entry knob G, page 1–4",
    "SYN: Data entry knob H, page 1–4",
    "SYN: Pitch Bend",
    "SYN: Aftertouch",
    "SYN: Mod Wheel",
    "SYN: Breath Controller",
    "CC: CC1–16 Values",
    "FILTER: Attack Time",
    "FILTER: Decay Time",
    "FILTER: Sustain Level",
    "FILTER: Release Time",
    "FILTER: Frequency",
    "FILTER: Data entry knob F",
    "FILTER: Data entry knob G",
    "FILTER: Envelope Depth",
    "FILTER: Env. Delay",
    "FILTER: Key Tracking",
]

LFO1_SPECIFIC = []

LFO2_SPECIFIC = [
    "LFO1: Speed",
    "LFO1: Multiplier",
    "LFO1: Fade In/Out",
    "LFO1: Waveform",
    "LFO1: Start Phase",
    "LFO1: Trig Mode",
    "LFO1: Depth",
]

LFO3_SPECIFIC = LFO2_SPECIFIC + [
    "LFO2: Speed",
    "LFO2: Multiplier",
    "LFO2: Fade In/Out",
    "LFO2: Waveform",
    "LFO2: Start Phase",
    "LFO2: Trig Mode",
    "LFO2: Depth",
]

# LFO Parameters
LFO1_PARAMS = {
    "SPD": {"cc": 102, "nrpn": 42, "default": 48},
    "MULT": {
        "cc": 103,
        "nrpn": 43,
        "max_midi": 11,
        "max_val": 2000,
        "min_val": 1,
        "default": 2,
    },
    "FADE": {"cc": 104, "nrpn": 44, "max_val": 63, "min_val": -64, "default": 0},
    "DEST": {
        "cc": 105,
        "nrpn": 45,
        "max_midi": 50,
        "min_midi": 25,
        "max_val": 50,
        "min_val": 25,
        "default": "none",
        "options": BASE_DESTINATIONS,
    },
    "WAVE": {
        "cc": 106,
        "nrpn": 46,
        "max_midi": 6,
        "max_val": 6,
        "default": "sine",
        "options": ["tri", "sine", "sqr", "saw", "expo", "ramp", "rand"],
    },
    "SPH": {"cc": 107, "nrpn": 47},
    "MODE": {
        "cc": 108,
        "nrpn": 48,
        "max_midi": 4,
        "max_val": 4,
        "default": "free",
        "options": ["free", "trig", "hold", "one", "half"],
    },
    "DEP": {"cc": 109, "nrpn": 49},
}

LFO2_PARAMS = {
    "SPD": {"cc": 111, "nrpn": 50, "default": 48},
    "MULT": {
        "cc": 112,
        "nrpn": 51,
        "max_midi": 11,
        "max_val": 2000,
        "min_val": 1,
        "default": 2,
    },
    "FADE": {"cc": 113, "nrpn": 52, "max_val": 63, "min_val": -64, "default": 0},
    "DEST": {
        "cc": 114,
        "nrpn": 53,
        "max_midi": 50,
        "min_midi": 25,
        "max_val": 50,
        "min_val": 25,
        "default": "none",
        "options": LFO2_SPECIFIC + BASE_DESTINATIONS,
    },
    "WAVE": {
        "cc": 115,
        "nrpn": 54,
        "max_midi": 6,
        "max_val": 6,
        "default": "sine",
        "options": ["tri", "sine", "sqr", "saw", "expo", "ramp", "rand"],
    },
    "SPH": {"cc": 116, "nrpn": 55},
    "MODE": {
        "cc": 117,
        "nrpn": 56,
        "max_midi": 4,
        "max_val": 4,
        "default": "free",
        "options": ["free", "trig", "hold", "one", "half"],
    },
    "DEP": {"cc": 118, "nrpn": 57},
}

LFO3_PARAMS = {
    "SPD": {"cc": 121, "nrpn": 58, "default": 48},
    "MULT": {
        "cc": 122,
        "nrpn": 59,
        "max_midi": 11,
        "max_val": 2000,
        "min_val": 1,
        "default": 2,
    },
    "FADE": {"cc": 123, "nrpn": 60, "max_val": 63, "min_val": -64, "default": 0},
    "DEST": {
        "cc": 124,
        "nrpn": 61,
        "max_midi": 50,
        "min_midi": 25,
        "max_val": 50,
        "min_val": 25,
        "default": "none",
        "options": LFO3_SPECIFIC + BASE_DESTINATIONS,
    },
    "WAVE": {
        "cc": 125,
        "nrpn": 62,
        "max_midi": 6,
        "max_val": 6,
        "default": "sine",
        "options": ["tri", "sine", "sqr", "saw", "expo", "ramp", "rand"],
    },
    "SPH": {"cc": 126, "nrpn": 70},
    "MODE": {
        "cc": 127,
        "nrpn": 71,
        "max_midi": 4,
        "max_val": 4,
        "default": "free",
        "options": ["free", "trig", "hold", "one", "half"],
    },
    "DEP": {"cc": 128, "nrpn": 72},
}

# FMDRUM Parameters
FMDRUM_PARAMS = {
    "page_1": {
        "tune": {"cc": 40, "nrpn": 73, "max_val": 60, "min_val": -60, "default": 0},
        "stim": {"cc": 41, "nrpn": 74},
        "sdep": {"cc": 42, "nrpn": 75},
        "algo": {
            "cc": 43,
            "nrpn": 76,
            "max_midi": 6,
            "max_val": 7,
            "min_val": 1,
            "default": 1,
        },
        "OP.C": {"cc": 44, "nrpn": 77},
        "OP.AB": {"cc": 45, "nrpn": 78},
        "FDBK": {"cc": 46, "nrpn": 79},
        "FOLD": {"cc": 47, "nrpn": 80},
    },
    "page_2": {
        "RATIO1": {
            "cc": 48,
            "nrpn": 81,
            "max_val": 31.75,
            "min_val": 0.001,
            "default": 0.500,
        },
        "DEC1": {"cc": 49, "nrpn": 82},
        "END1": {"cc": 50, "nrpn": 83},
        "MOD1": {"cc": 51, "nrpn": 84},
        "RATIO2": {
            "cc": 52,
            "nrpn": 85,
            "max_val": 31.75,
            "min_val": 0.001,
            "default": 0.500,
        },
        "DEC2": {"cc": 53, "nrpn": 86},
        "END2": {"cc": 54, "nrpn": 87},
        "MOD2": {"cc": 55, "nrpn": 88},
    },
    "page_3": {
        "HOLD": {"cc": 56, "nrpn": 89},
        "DEC": {"cc": 57, "nrpn": 90},
        "PH.C": {"cc": 58, "nrpn": 91, "max_midi": 91, "max_val": 91},
        "LEV": {"cc": 59, "nrpn": 92},
        "NRST": {"cc": 62, "nrpn": 95, "max_midi": 1, "max_val": 1},
        "NRM": {"cc": 63, "nrpn": 96, "max_midi": 1, "max_val": 1},
    },
    "page_4": {
        "NHLD": {"cc": 70, "nrpn": 97},
        "NDEC": {"cc": 71, "nrpn": 98},
        "TRAN": {"cc": 72, "nrpn": 99, "max_midi": 124, "max_val": 124},
        "TLEV": {"cc": 73, "nrpn": 100},
        "BASE": {"cc": 74, "nrpn": 101},
        "WDTH": {"cc": 75, "nrpn": 102},
        "GRAN": {"cc": 76, "nrpn": 103},
        "NLEV": {"cc": 77, "nrpn": 104},
    },
}

# FMTONE Parameters
FMTONE_PARAMS = {
    "page_1": {
        "ALGO": {
            "cc": 40,
            "nrpn": 73,
            "max_midi": 7,
            "min_midi": 0,
            "max_val": 8,
            "min_val": 1,
            "default": 1,
        },
        "C": {
            "cc": 41,
            "nrpn": 74,
            "max_midi": 18,
            "min_midi": 0,
            "max_val": 16,
            "min_val": 0.25,
            "default": 1.00,
        },
        "A": {
            "cc": 42,
            "nrpn": 75,
            "max_midi": 35,
            "min_midi": 0,
            "max_val": 16,
            "min_val": 0.25,
            "default": 1.00,
        },
        "B": {
            "cc": 43,
            "nrpn": 76,
            "max_midi": 3,
            "min_midi": 0,
            "max_val": [16, 16],
            "min_val": [0.25, 0.25],
            "default": [1.00, 1.00],
        },
        "HARM": {
            "cc": 44,
            "nrpn": 77,
            "max_midi": 37,
            "min_midi": 90,
            "max_val": 26,
            "min_val": -26,
            "default": 0.00,
        },
        "DTUN": {
            "cc": 45,
            "nrpn": 78,
            "max_midi": 127,
            "min_midi": 0,
            "max_val": 127,
            "min_val": 0,
            "default": 0,
        },
        "FDBK": {
            "cc": 46,
            "nrpn": 79,
            "max_midi": 127,
            "min_midi": 0,
            "max_val": 127,
            "min_val": 0,
            "default": 0,
        },
        "MIX": {
            "cc": 47,
            "nrpn": 80,
            "max_midi": 127,
            "min_midi": 0,
            "max_val": 63,
            "min_val": -63,
            "default": -63,
        },
    },
    "page_2": {
        "A": {
            "atk": {
                "cc": 48,
                "nrpn": 81,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 0,
            },
            "dec": {
                "cc": 49,
                "nrpn": 82,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 32,
            },
            "end": {
                "cc": 50,
                "nrpn": 83,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 127,
            },
            "lev": {
                "cc": 51,
                "nrpn": 84,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 0,
            },
        },
        "B": {
            "atk": {
                "cc": 48,
                "nrpn": 81,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 0,
            },
            "dec": {
                "cc": 49,
                "nrpn": 82,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 32,
            },
            "end": {
                "cc": 50,
                "nrpn": 83,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 127,
            },
            "lev": {
                "cc": 51,
                "nrpn": 84,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 0,
            },
        },
    },
    "page_3": {
        "ADEL": {
            "cc": 56,
            "nrpn": 89,
            "max_midi": 127,
            "min_midi": 0,
            "max_val": 127,
            "min_val": 0,
            "default": 0,
        },
        "ATRG": {
            "cc": 57,
            "nrpn": 90,
            "max_midi": 1,
            "min_midi": 0,
            "max_val": 1,
            "min_val": 0,
            "default": 1,
        },
        "ARST": {
            "cc": 58,
            "nrpn": 91,
            "max_midi": 1,
            "min_midi": 0,
            "max_val": 1,
            "min_val": 0,
            "default": 1,
        },
        "PHRT": {
            "cc": 59,
            "nrpn": 92,
            "max_midi": 4,
            "min_midi": 0,
            "options": ["off", "all", "c", "a+b", "a+b2"],
            "default": "all",
        },
        "BDEL": {
            "cc": 60,
            "nrpn": 93,
            "max_midi": 127,
            "min_midi": 0,
            "max_val": 127,
            "min_val": 0,
            "default": 0,
        },
        "BTRG": {
            "cc": 61,
            "nrpn": 94,
            "max_midi": 1,
            "min_midi": 0,
            "max_val": 1,
            "min_val": 0,
            "default": 1,
        },
        "BRST": {
            "cc": 62,
            "nrpn": 95,
            "max_midi": 1,
            "min_midi": 0,
            "max_val": 1,
            "min_val": 0,
            "default": 1,
        },
    },
    "page_4": {
        "Ratio_Offset": {
            "C": {
                "cc": 70,
                "nrpn": 97,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 0.999,
                "min_val": -1.00,
                "default": 0.00,
            },
            "A": {
                "cc": 71,
                "nrpn": 98,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 0.999,
                "min_val": -1.00,
                "default": 0.00,
            },
            "B1": {
                "cc": 72,
                "nrpn": 99,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 0.999,
                "min_val": -1.00,
                "default": 0.00,
            },
            "B2": {
                "cc": 73,
                "nrpn": 100,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 0.999,
                "min_val": -1.00,
                "default": 0.00,
            },
        },
        "Key_Track": {
            "A": {
                "cc": 75,
                "nrpn": 102,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 0,
            },
            "B1": {
                "cc": 76,
                "nrpn": 103,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 0,
            },
            "B2": {
                "cc": 77,
                "nrpn": 104,
                "max_midi": 127,
                "min_midi": 0,
                "max_val": 127,
                "min_val": 0,
                "default": 0,
            },
        },
    },
}

# Filter Parameters
MULTI_MODE_FILTER_PARAMS = {
    "ATK": {"cc": 20, "nrpn": 16},
    "DEC": {"cc": 21, "nrpn": 17, "default": 64},
    "SUS": {"cc": 22, "nrpn": 18},
    "REL": {"cc": 23, "nrpn": 19, "default": 64},
    "FREQ": {"cc": 16, "nrpn": 20, "default": 127},
    "RESO": {"cc": 17, "nrpn": 21},
    "TYPE": {"cc": 18, "nrpn": 22},
    "ENV Depth": {"cc": 24, "nrpn": 26, "max_val": 64, "min_val": -64},
}
