elektron_fn_to_midi = {
    "fmdrum": {
        "page_1": {
            "tune": {
                "midi": {"cc_msb": "40", "nrpn_lsb": "1", "nrpn_msb": "73"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 60,
                "min_value": -60,
                "default_value": 0,
            },
            "stim": {
                "midi": {"cc_msb": "41", "nrpn_lsb": "1", "nrpn_msb": "74"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "sdep": {
                "midi": {"cc_msb": "42", "nrpn_lsb": "1", "nrpn_msb": "75"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "algo": {
                "midi": {"cc_msb": "43", "nrpn_lsb": "1", "nrpn_msb": "76"},
                "max_midi_value": 6,
                "min_midi_value": 0,
                "max_value": 7,
                "min_value": 1,
                "default_value": 1,
            },
            "OP.C": {
                "midi": {"cc_msb": "44", "nrpn_lsb": "1", "nrpn_msb": "77"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "OP.AB": {
                "midi": {"cc_msb": "45", "nrpn_lsb": "1", "nrpn_msb": "78"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "FDBK": {
                "midi": {"cc_msb": "46", "nrpn_lsb": "1", "nrpn_msb": "79"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "FOLD": {
                "midi": {"cc_msb": "47", "nrpn_lsb": "1", "nrpn_msb": "80"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            }
        },
        "page_2": {
            "RATIO1": {
                "midi": {"cc_msb": "48", "nrpn_lsb": "1", "nrpn_msb": "81"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 31.75,
                "min_value": 0.001,
                "default_value": 0.500,
            },
            "DEC1": {
                "midi": {"cc_msb": "49", "nrpn_lsb": "1", "nrpn_msb": "82"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "END1": {
                "midi": {"cc_msb": "50", "nrpn_lsb": "1", "nrpn_msb": "83"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "MOD1": {
                "midi": {"cc_msb": "51", "nrpn_lsb": "1", "nrpn_msb": "84"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "RATIO2": {
                "midi": {"cc_msb": "52", "nrpn_lsb": "1", "nrpn_msb": "85"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 31.75,
                "min_value": 0.001,
                "default_value": 0.500,
            },
            "DEC2": {
                "midi": {"cc_msb": "53", "nrpn_lsb": "1", "nrpn_msb": "86"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "END2": {
                "midi": {"cc_msb": "54", "nrpn_lsb": "1", "nrpn_msb": "87"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "MOD2": {
                "midi": {"cc_msb": "55", "nrpn_lsb": "1", "nrpn_msb": "88"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            }
        },
        "page_3": {
            "HOLD": {
                "midi": {"cc_msb": "56", "nrpn_lsb": "1", "nrpn_msb": "89"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "DEC": {
                "midi": {"cc_msb": "57", "nrpn_lsb": "1", "nrpn_msb": "90"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "PH.C": {
                "midi": {"cc_msb": "58", "nrpn_lsb": "1", "nrpn_msb": "91"},
                "max_midi_value": 91,
                "min_midi_value": 0,
                "max_value": 91,
                "min_value": 0,
                "default_value": 0,
            },
            "LEV": {
                "midi": {"cc_msb": "59", "nrpn_lsb": "1", "nrpn_msb": "92"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "NRST": {
                "midi": {"cc_msb": "62", "nrpn_lsb": "1", "nrpn_msb": "95"},
                "max_midi_value": 1,
                "min_midi_value": 0,
                "max_value": 1,
                "min_value": 0,
                "default_value": 0,
            },
            "NRM": {
                "midi": {"cc_msb": "63", "nrpn_lsb": "1", "nrpn_msb": "96"},
                "max_midi_value": 1,
                "min_midi_value": 0,
                "max_value": 1,
                "min_value": 0,
                "default_value": 0,
            }
        },
        "page_4": {
            "NHLD": {
                "midi": {"cc_msb": "70", "nrpn_lsb": "1", "nrpn_msb": "97"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "NDEC": {
                "midi": {"cc_msb": "71", "nrpn_lsb": "1", "nrpn_msb": "98"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "TRAN": {
                "midi": {"cc_msb": "72", "nrpn_lsb": "1", "nrpn_msb": "99"},
                "max_midi_value": 124,
                "min_midi_value": 0,
                "max_value": 124,
                "min_value": 0,
                "default_value": 0,
            },
            "TLEV": {
                "midi": {"cc_msb": "73", "nrpn_lsb": "1", "nrpn_msb": "100"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "BASE": {
                "midi": {"cc_msb": "74", "nrpn_lsb": "1", "nrpn_msb": "101"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "WDTH": {
                "midi": {"cc_msb": "75", "nrpn_lsb": "1", "nrpn_msb": "102"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "GRAN": {
                "midi": {"cc_msb": "76", "nrpn_lsb": "1", "nrpn_msb": "103"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "NLEV": {
                "midi": {"cc_msb": "77", "nrpn_lsb": "1", "nrpn_msb": "104"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            }
        }
    },
    "fmtone": {
        "page_1": {
            "ALGO": {
                "midi": {"cc_msb": "40", "nrpn_lsb": "1", "nrpn_msb": "73"},
                "max_midi_value": 7,
                "min_midi_value": 0,
                "max_value": 8,
                "min_value": 1,
                "default_value": 0,
            },
            "C": {
                "midi": {"cc_msb": "41", "nrpn_lsb": "1", "nrpn_msb": "74"},
                "max_midi_value": 18,
                "min_midi_value": 0,
                "max_value": 16,
                "min_value": 0.25,
                "default_value": 1.00,
            },
            "A": {
                "midi": {"cc_msb": "42", "nrpn_lsb": "1", "nrpn_msb": "75"},
                "max_midi_value": 35,
                "min_midi_value": 0,
                "max_value": 16,
                "min_value": 0.25,
                "default_value": 1.00,
            },
            "B": {
                "midi": {"cc_msb": "43", "nrpn_lsb": "1", "nrpn_msb": "76"},
                "max_midi_value": 3,
                "min_midi_value": 0,
                "max_value": [16, 16],
                "min_value": [0.25, 0.25],
                "default_value": [1.00, 1.00],
            },
            "HARM": {
                "midi": {"cc_msb": "44", "nrpn_lsb": "1", "nrpn_msb": "77"},
                "max_midi_value": 37,
                "min_midi_value": 90,
                "max_value": 26,
                "min_value": -26,
                "default_value": 0.00,
            },
            "DTUN": {
                "midi": {"cc_msb": "45", "nrpn_lsb": "1", "nrpn_msb": "78"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "FDBK": {
                "midi": {"cc_msb": "46", "nrpn_lsb": "1", "nrpn_msb": "79"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "MIX": {
                "midi": {"cc_msb": "47", "nrpn_lsb": "1", "nrpn_msb": "80"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 63,
                "min_value": -63,
                "default_value": -63,
            },
        },
        "page_2": {
            "A": {
                "atk": {
                    "midi": {"cc_msb": "48", "nrpn_lsb": "1", "nrpn_msb": "81"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 0,
                },
                "dec": {
                    "midi": {"cc_msb": "49", "nrpn_lsb": "1", "nrpn_msb": "82"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 32,
                },
                "end": {
                    "midi": {"cc_msb": "50", "nrpn_lsb": "1", "nrpn_msb": "83"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 127,
                },
                "lev": {
                    "midi": {"cc_msb": "51", "nrpn_lsb": "1", "nrpn_msb": "84"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 0,
                }
            },
            "B": {
                "atk": {
                    "midi": {"cc_msb": "48", "nrpn_lsb": "1", "nrpn_msb": "81"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 0,
                },
                "dec": {
                    "midi": {"cc_msb": "49", "nrpn_lsb": "1", "nrpn_msb": "82"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 32,
                },
                "end": {
                    "midi": {"cc_msb": "50", "nrpn_lsb": "1", "nrpn_msb": "83"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 127,
                },
                "lev": {
                    "midi": {"cc_msb": "51", "nrpn_lsb": "1", "nrpn_msb": "84"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 0,
                }
            }
        },
        "page_3": {
            "ADEL": {
                "midi": {"cc_msb": "56", "nrpn_lsb": "1", "nrpn_msb": "89"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "ATRG": {
                "midi": {"cc_msb": "57", "nrpn_lsb": "1", "nrpn_msb": "90"},
                "max_midi_value": 1,
                "min_midi_value": 0,
                "max_value": 1,
                "min_value": 0,
                "default_value": 1,
            },
            "ARST": {
                "midi": {"cc_msb": "58", "nrpn_lsb": "1", "nrpn_msb": "91"},
                "max_midi_value": 1,
                "min_midi_value": 0,
                "max_value": 1,
                "min_value": 0,
                "default_value": 1,
            },
            "PHRT": {
                "midi": {"cc_msb": "59", "nrpn_lsb": "1", "nrpn_msb": "92"},
                "max_midi_value": 4,
                "min_midi_value": 0,
                "options": ["off", "all", "c", "a+b", "a+b2"],
                "default_value": "all",
            },
            "BDEL": {
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "BTRG": {
                "midi": {"cc_msb": "61", "nrpn_lsb": "1", "nrpn_msb": "94"},
                "max_midi_value": 1,
                "min_midi_value": 0,
                "max_value": 1,
                "min_value": 0,
                "default_value": 1,
            },
            "BRST": {
                "midi": {"cc_msb": "62", "nrpn_lsb": "1", "nrpn_msb": "95"},
                "max_midi_value": 1,
                "min_midi_value": 0,
                "max_value": 1,
                "min_value": 0,
                "default_value": 1,
            }
        },
        "page_4": {
            "Ratio_Offset": {
                "C": {
                    "midi": {"cc_msb": "70", "nrpn_lsb": "1", "nrpn_msb": "97"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": +0.999,
                    "min_value": -1.00,
                    "default_value": 0.00,
                },
                "A": {
                    "midi": {"cc_msb": "71", "nrpn_lsb": "1", "nrpn_msb": "98"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": +0.999,
                    "min_value": -1.00,
                    "default_value": 0.00,
                },
                "B1": {
                    "midi": {"cc_msb": "72", "nrpn_lsb": "1", "nrpn_msb": "99"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": +0.999,
                    "min_value": -1.00,
                    "default_value": 0.00,
                },
                "B2": {
                    "midi": {"cc_msb": "73", "nrpn_lsb": "1", "nrpn_msb": "100"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": +0.999,
                    "min_value": -1.00,
                    "default_value": 0.00,
                }
            },
            "Key_Track": {
                "A": {
                    "midi": {"cc_msb": "75", "nrpn_lsb": "1", "nrpn_msb": "102"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 0,
                },
                "B1": {
                    "midi": {"cc_msb": "76", "nrpn_lsb": "1", "nrpn_msb": "103"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 0,
                },
                "B2": {
                    "midi": {"cc_msb": "77", "nrpn_lsb": "1", "nrpn_msb": "104"},
                    "max_midi_value": 127,
                    "min_midi_value": 0,
                    "max_value": 127,
                    "min_value": 0,
                    "default_value": 0,
                }
            }
        }
    },
    "swarmer": {
        "page_1": {
            "TUNE": {
                "midi": {"cc_msb": "40", "nrpn_lsb": "1", "nrpn_msb": "73"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 60,
                "min_value": -60,
                "default_value": 0,
            },
            "SWRM": {
                "midi": {"cc_msb": "41", "nrpn_lsb": "1", "nrpn_msb": "74"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 120,
                "min_value": 0,
                "default_value": 80,
            },
            "DET": {
                "midi": {"cc_msb": "42", "nrpn_lsb": "1", "nrpn_msb": "75"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 70,
            },
            "MIX": {
                "midi": {"cc_msb": "43", "nrpn_lsb": "1", "nrpn_msb": "76"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 127,
            },
            "M.OCT": {
                "midi": {"cc_msb": "44", "nrpn_lsb": "1", "nrpn_msb": "77"},
                "max_midi_value": 2,
                "min_midi_value": 0,
                "max_value": 2,
                "min_value": 0,
                "default_value": 0,
            },
            "MAIN": {
                "midi": {"cc_msb": "45", "nrpn_lsb": "1", "nrpn_msb": "78"},
                "max_midi_value": 120,
                "min_midi_value": 0,
                "max_value": 120,
                "min_value": 0,
                "default_value": 80,
            },
            "ANIM": {
                "midi": {"cc_msb": "46", "nrpn_lsb": "1", "nrpn_msb": "79"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 15,
            },
            "N.MOD": {
                "midi": {"cc_msb": "47", "nrpn_lsb": "1", "nrpn_msb": "80"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 20,
            }
        }
    },
    "wavetone": {
        "page_1": {
            "TUN1": {
                "midi": {"cc_msb": "40", "nrpn_lsb": "1", "nrpn_msb": "73"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 60,
                "min_value": -60,
                "default_value": 0,
            },
            "WAV1": {
                "midi": {"cc_msb": "41", "nrpn_lsb": "1", "nrpn_msb": "74"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 120,
                "min_value": 0,
                "default_value": 0,
            },
            "PD1": {
                "midi": {"cc_msb": "42", "nrpn_lsb": "1", "nrpn_msb": "75"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 100,
                "min_value": 0,
                "default_value": 50,
            },
            "LEV1": {
                "midi": {"cc_msb": "43", "nrpn_lsb": "1", "nrpn_msb": "76"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 100,
            },
            "TUN2": {
                "midi": {"cc_msb": "44", "nrpn_lsb": "1", "nrpn_msb": "77"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 60,
                "min_value": -60,
                "default_value": 0,
            },
            "WAV2": {
                "midi": {"cc_msb": "45", "nrpn_lsb": "1", "nrpn_msb": "78"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 120,
                "min_value": 0,
                "default_value": 0,
            },
            "PD2": {
                "midi": {"cc_msb": "46", "nrpn_lsb": "1", "nrpn_msb": "79"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 100,
                "min_value": 0,
                "default_value": 50,
            },
            "LEV2": {
                "midi": {"cc_msb": "47", "nrpn_lsb": "1", "nrpn_msb": "80"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 100,
            }
        },
        "page_2": {
            "OFS1": {
                "midi": {"cc_msb": "48", "nrpn_lsb": "1", "nrpn_msb": "81"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 10,
                "min_value": -10,
                "default_value": 0,
            },
            "TBL1": {
                "midi": {"cc_msb": "49", "nrpn_lsb": "1", "nrpn_msb": "82"},
                "max_midi_value": 1,
                "min_midi_value": 0,
                "options": ["prim", "harm"],
                "default_value": "prim",
            },
            "MOD": {
                "midi": {"cc_msb": "50", "nrpn_lsb": "1", "nrpn_msb": "83"},
                "max_midi_value": 3,
                "min_midi_value": 0,
                "options": ["off", "ring mod", "ring mod fixed", "hard sync"],
                "default_value": "off",
            },
            "RSET": {
                "midi": {"cc_msb": "51", "nrpn_lsb": "1", "nrpn_msb": "84"},
                "max_midi_value": 2,
                "min_midi_value": 0,
                "options": ["off", "on", "random"],
                "default_value": "on",
            },
            "OFS2": {
                "midi": {"cc_msb": "52", "nrpn_lsb": "1", "nrpn_msb": "85"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 10,
                "min_value": -10,
                "default_value": 0,
            },
            "TBL2": {
                "midi": {"cc_msb": "53", "nrpn_lsb": "1", "nrpn_msb": "86"},
                "max_midi_value": 1,
                "min_midi_value": 0,
                "options": ["prim", "harm"],
                "default_value": "prim",
            },
            "DRIF": {
                "midi": {"cc_msb": "55", "nrpn_lsb": "1", "nrpn_msb": "88"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            }
        },
        "page_3": {
            "ATK": {
                "midi": {"cc_msb": "56", "nrpn_lsb": "1", "nrpn_msb": "89"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "HOLD": {
                "midi": {"cc_msb": "57", "nrpn_lsb": "1", "nrpn_msb": "90"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 127,
            },
            "DEC": {
                "midi": {"cc_msb": "58", "nrpn_lsb": "1", "nrpn_msb": "91"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 127,
            },
            "NLEV": {
                "midi": {"cc_msb": "59", "nrpn_lsb": "1", "nrpn_msb": "92"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "BASE": {
                "midi": {"cc_msb": "60", "nrpn_lsb": "1", "nrpn_msb": "93"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "WDTH": {
                "midi": {"cc_msb": "61", "nrpn_lsb": "1", "nrpn_msb": "94"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 127,
            },
            "TYPE": {
                "midi": {"cc_msb": "62", "nrpn_lsb": "1", "nrpn_msb": "95"},
                "max_midi_value": 2,
                "min_midi_value": 0,
                "options": ["grain nose", "tuned noise", "sample and hold noise"],
                "default_value": 0,
            },
            "CHAR": {
                "midi": {"cc_msb": "63", "nrpn_lsb": "1", "nrpn_msb": "96"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            }
        }
    },
    "Multi-mode filter": {
        "ATK": {
            "midi": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "DEC": {
            "midi": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "SUS": {
            "midi": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "REL": {
            "midi": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "FREQ": {
            "midi": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 127,
        },
        "RESO": {
            "midi": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "TYPE": {
            "midi": {"cc_msb": "18", "nrpn_lsb": "1", "nrpn_msb": "22"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "ENV Depth": {
            "midi": {"cc_msb": "24", "nrpn_lsb": "1", "nrpn_msb": "26"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 64,
            "min_value": -64,
            "default_value": 0,
        },
    },
    "Lowpass 4 filter": {
        "ATK": {
            "midi": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "DEC": {
            "midi": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "SUS": {
            "midi": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "REL": {
            "midi": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "FREQ": {
            "midi": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "RESO": {
            "midi": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "ENV.Depth": {
            "midi": {"cc_msb": "24", "nrpn_lsb": "1", "nrpn_msb": "26"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 64,
            "min_value": -64,
            "default_value": 0,
        },
    },
    "Legacy LP/HP filter": {
        "ATK": {
            "midi": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "DEC": {
            "midi": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "SUS": {
            "midi": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "REL": {
            "midi": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "FREQ": {
            "midi": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "RESO": {
            "midi": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "TYPE(lowpass/highpass)": {
            "midi": {"cc_msb": "18", "nrpn_lsb": "1", "nrpn_msb": "22"},
            "max_midi_value": 2,
            "min_midi_value": 0,
            "options": ["lowpass", "highpass", "off"],
            "default_value": 0,
        },
        "ENV.Depth": {
            "midi": {"cc_msb": "24", "nrpn_lsb": "1", "nrpn_msb": "26"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 64,
            "min_value": -64,
            "default_value": 0,
        },
    },
    "Comb- filter": {
        "ATK": {
            "midi": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "DEC": {
            "midi": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "SUS": {
            "midi": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "REL": {
            "midi": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "FREQ": {
            "midi": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 127,
        },
        "FDBK": {
            "midi": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "LPF": {
            "midi": {"cc_msb": "18", "nrpn_lsb": "1", "nrpn_msb": "22"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 127,
        },
        "ENV.Depth": {
            "midi": {"cc_msb": "24", "nrpn_lsb": "1", "nrpn_msb": "26"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 64,
            "min_value": -64,
            "default_value": 0,
        },
    },
    "Comb+ filter": {
        "ATK": {
            "midi": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "DEC": {
            "midi": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "SUS": {
            "midi": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "REL": {
            "midi": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "FREQ": {
            "midi": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 127,
        },
        "FDBK": {
            "midi": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "LPF": {
            "midi": {"cc_msb": "18", "nrpn_lsb": "1", "nrpn_msb": "22"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 127,
        },
        "ENV.Depth": {
            "midi": {"cc_msb": "24", "nrpn_lsb": "1", "nrpn_msb": "26"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 64,
            "min_value": -64,
            "default_value": 0,
        },
    },
    "Equalizer filter": {
        "ATK": {
            "midi": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "DEC": {
            "midi": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "SUS": {
            "midi": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "REL": {
            "midi": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 64,
        },
        "FREQ": {
            "midi": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 127,
        },
        "GAIN": {
            "midi": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "Q": {
            "midi": {"cc_msb": "18", "nrpn_lsb": "1", "nrpn_msb": "22"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "ENV.Depth": {
            "midi": {"cc_msb": "24", "nrpn_lsb": "1", "nrpn_msb": "26"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 64,
            "min_value": -64,
            "default_value": 0,
        },
    },
    "base/width filter": {
        "ENV.Delay": {
            "midi": {"cc_msb": "19", "nrpn_lsb": "1", "nrpn_msb": "23"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "KEY.Tracking": {
            "midi": {"cc_msb": "26", "nrpn_lsb": "1", "nrpn_msb": "69"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "BASE": {
            "midi": {"cc_msb": "27", "nrpn_lsb": "1", "nrpn_msb": "24"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "WDTH": {
            "midi": {"cc_msb": "28", "nrpn_lsb": "1", "nrpn_msb": "25"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "Env Reset": {
            "midi": {"cc_msb": "25", "nrpn_lsb": "1", "nrpn_msb": "68"},
            "max_midi_value": 1,
            "min_midi_value": 0,
            "options": ["off", "on"],
            "default_value": "off",
        },
    },
    "amp_page": {
        "ATK": {
            "midi": {"cc_msb": "84", "nrpn_lsb": "1", "nrpn_msb": "30"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 8,
        },
        "HOLD": {
            "midi": {"cc_msb": "85", "nrpn_lsb": "1", "nrpn_msb": "31"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 127,
        },
        "DEC": {
            "midi": {"cc_msb": "86", "nrpn_lsb": "1", "nrpn_msb": "32"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 32,
        },
        "SUS": {
            "midi": {"cc_msb": "87", "nrpn_lsb": "1", "nrpn_msb": "33"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 96,
        },
        "REL": {
            "midi": {"cc_msb": "88", "nrpn_lsb": "1", "nrpn_msb": "34"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 24,
        },
        "Env. RSET": {
            "midi": {"cc_msb": "92", "nrpn_lsb": "1", "nrpn_msb": "41"},
            "max_midi_value": 1,
            "min_midi_value": 0,
            "options": ["off", "on"],
            "default_value": "on",
        },
        "MODE": {
            "midi": {"cc_msb": "91", "nrpn_lsb": "1", "nrpn_msb": "40"},
            "max_midi_value": 1,
            "min_midi_value": 0,
            "options": ["AHD", "ADSR"],
            "default_value": "ADSR",
        },
        "PAN": {
            "midi": {"cc_msb": "89", "nrpn_lsb": "1", "nrpn_msb": "38"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 64,
            "min_value": -64,
            "default_value": 0,
        },
        "VOL": {
            "midi": {"cc_msb": "90", "nrpn_lsb": "1", "nrpn_msb": "39"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 110,
        },
    },
    "fx_page": {
        "BR": {
            "midi": {"cc_msb": "78", "nrpn_lsb": "1", "nrpn_msb": "5"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "OVER": {
            "midi": {"cc_msb": "81", "nrpn_lsb": "1", "nrpn_msb": "8"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "SRR": {
            "midi": {"cc_msb": "79", "nrpn_lsb": "1", "nrpn_msb": "6"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "SR.RT(pre/post)": {
            "midi": {"cc_msb": "80", "nrpn_lsb": "1", "nrpn_msb": "7"},
            "max_midi_value": 1,
            "min_midi_value": 0,
            "options": ["pre", "post"],
            "default_value": "pre",
        },
        "OD.RT(pre/post)": {
            "midi": {"cc_msb": "82", "nrpn_lsb": "1", "nrpn_msb": "9"},
            "max_midi_value": 1,
            "min_midi_value": 0,
            "options": ["pre", "post"],
            "default_value": "pre",
        },
        "DEL": {
            "midi": {"cc_msb": "30", "nrpn_lsb": "1", "nrpn_msb": "36"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "REV": {
            "midi": {"cc_msb": "31", "nrpn_lsb": "1", "nrpn_msb": "37"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
        "CHR": {
            "midi": {"cc_msb": "29", "nrpn_lsb": "1", "nrpn_msb": "35"},
            "max_midi_value": 127,
            "min_midi_value": 0,
            "max_value": 127,
            "min_value": 0,
            "default_value": 0,
        },
    },
    "lfo": {
        "lfo_1": {
            "SPD": {
                "midi": {"cc_msb": "102", "nrpn_lsb": "1", "nrpn_msb": "42"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 48,
            },
            "MULT": {
                "midi": {"cc_msb": "103", "nrpn_lsb": "1", "nrpn_msb": "43"},
                "max_midi_value": 11,
                "min_midi_value": 0,
                "max_value": 2000,
                "min_value": 1,
                "default_value": 2,
            },
            "FADE": {
                "midi": {"cc_msb": "104", "nrpn_lsb": "1", "nrpn_msb": "44"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 63,
                "min_value": -64,
                "default_value": 0,
            },
            "DEST": {
                "midi": {"cc_msb": "105", "nrpn_lsb": "1", "nrpn_msb": "45"},
                "max_midi_value": 50,
                "min_midi_value": 25,
                "options": [
                    "none",
                    "FILTER: Base",
                    "FILTER: Width",
                    "FILTER: Env. Reset",
                    "AMP: Attack Time",
                    "AMP: Hold Time",
                    "AMP: Decay Time",
                    "AMP: Sustain Level",
                    "AMP: Release Time",
                    "AMP: Pan",
                    "AMP: Volume",
                    "FX: Delay Send",
                    "FX: Reverb Send",
                    "FX: Chorus Send",
                    "FX: Bit Reduction",
                    "FX: SRR",
                    "FX: SRR Routing",
                    "FX: Overdrive",
                    "SYN: Data entry knob A, page 1–4",
                    "SYN: Data entry knob B, page 1–4",
                    "SYN: Data entry knob C, page 1–4",
                    "SYN: Data entry knob D, page 1–4",
                    "SYN: Data entry knob E, page 1–4",
                    "SYN: Data entry knob F, page 1–4",
                    "SYN: Data entry knob G, page 1–4",
                    "SYN: Data entry knob H, page 1–4",
                    "SYN: Pitch Bend",
                    "SYN: Aftertouch",
                    "SYN: Mod Wheel",
                    "SYN: Breath Controller",
                    "CC: CC1–16 Values",
                    "FILTER: Attack Time",
                    "FILTER: Decay Time",
                    "FILTER: Sustain Level",
                    "FILTER: Release Time",
                    "FILTER: Frequency",
                    "FILTER: Data entry knob F",
                    "FILTER: Data entry knob G",
                    "FILTER: Envelope Depth",
                    "FILTER: Env. Delay",
                    "FILTER: Key Tracking"
                ],
                "default_value": "none",
            },
            "WAVE": {
                "midi": {"cc_msb": "106", "nrpn_lsb": "1", "nrpn_msb": "46"},
                "max_midi_value": 6,
                "min_midi_value": 0,
                "options": ["tri", "sine", "sqr", "saw", "expo", "ramp", "rand"],
                "default_value": "sine",
            },
            "SPH": {
                "midi": {"cc_msb": "107", "nrpn_lsb": "1", "nrpn_msb": "47"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "MODE": {
                "midi": {"cc_msb": "108", "nrpn_lsb": "1", "nrpn_msb": "48"},
                "max_midi_value": 4,
                "min_midi_value": 0,
                "options": ["free", "trig", "hold", "one", "half"],
                "default_value": "free",
            },
            "DEP": {
                "midi": {"cc_msb": "109", "nrpn_lsb": "1", "nrpn_msb": "49"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
        },
        "lfo_2": {
            "SPD": {
                "midi": {"cc_msb": "111", "nrpn_lsb": "1", "nrpn_msb": "50"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 48,
            },
            "MULT": {
                "midi": {"cc_msb": "112", "nrpn_lsb": "1", "nrpn_msb": "51"},
                "max_midi_value": 11,
                "min_midi_value": 0,
                "max_value": 2000,
                "min_value": 1,
                "default_value": 2,
            },
            "FADE": {
                "midi": {"cc_msb": "113", "nrpn_lsb": "1", "nrpn_msb": "52"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 63,
                "min_value": -64,
                "default_value": 0,
            },
            "DEST": {
                "midi": {"cc_msb": "114", "nrpn_lsb": "1", "nrpn_msb": "53"},
                "max_midi_value": 50,
                "min_midi_value": 25,
                "options": [
                    "none",
                    "LFO1: Speed",
                    "LFO1: Multiplier",
                    "LFO1: Fade In/Out",
                    "LFO1: Waveform",
                    "LFO1: Start Phase",
                    "LFO1: Trig Mode",
                    "LFO1: Depth",
                    "FILTER: Base",
                    "FILTER: Width",
                    "FILTER: Env. Reset",
                    "AMP: Attack Time",
                    "AMP: Hold Time",
                    "AMP: Decay Time",
                    "AMP: Sustain Level",
                    "AMP: Release Time",
                    "AMP: Pan",
                    "AMP: Volume",
                    "FX: Delay Send",
                    "FX: Reverb Send",
                    "FX: Chorus Send",
                    "FX: Bit Reduction",
                    "FX: SRR",
                    "FX: SRR Routing",
                    "FX: Overdrive",
                    "SYN: Data entry knob A, page 1–4",
                    "SYN: Data entry knob B, page 1–4",
                    "SYN: Data entry knob C, page 1–4",
                    "SYN: Data entry knob D, page 1–4",
                    "SYN: Data entry knob E, page 1–4",
                    "SYN: Data entry knob F, page 1–4",
                    "SYN: Data entry knob G, page 1–4",
                    "SYN: Data entry knob H, page 1–4",
                    "SYN: Pitch Bend",
                    "SYN: Aftertouch",
                    "SYN: Mod Wheel",
                    "SYN: Breath Controller",
                    "CC: CC1–16 Values",
                    "FILTER: Attack Time",
                    "FILTER: Decay Time",
                    "FILTER: Sustain Level",
                    "FILTER: Release Time",
                    "FILTER: Frequency",
                    "FILTER: Data entry knob F",
                    "FILTER: Data entry knob G",
                    "FILTER: Envelope Depth",
                    "FILTER: Env. Delay",
                    "FILTER: Key Tracking"
                ],
                "default_value": "none",
            },
            "WAVE": {
                "midi": {"cc_msb": "115", "nrpn_lsb": "1", "nrpn_msb": "54"},
                "max_midi_value": 6,
                "min_midi_value": 0,
                "options": ["tri", "sine", "sqr", "saw", "expo", "ramp", "rand"],
                "default_value": "sine",
            },
            "SPH": {
                "midi": {"cc_msb": "116", "nrpn_lsb": "1", "nrpn_msb": "55"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "Trig MODE": {
                "midi": {"cc_msb": "117", "nrpn_lsb": "1", "nrpn_msb": "56"},
                "max_midi_value": 4,
                "min_midi_value": 0,
                "options": ["free", "trig", "hold", "one", "half"],
                "default_value": "free",
            },
            "DEP": {
                "midi": {"cc_msb": "118", "nrpn_lsb": "1", "nrpn_msb": "57"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
        },
        "lfo_3": {
            "SPD": {
                "midi": {"cc_msb": "121", "nrpn_lsb": "1", "nrpn_msb": "58"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 48,
            },
            "MULT": {
                "midi": {"cc_msb": "122", "nrpn_lsb": "1", "nrpn_msb": "59"},
                "max_midi_value": 11,
                "min_midi_value": 0,
                "max_value": 2000,
                "min_value": 1,
                "default_value": 2,
            },
            "FADE": {
                "midi": {"cc_msb": "123", "nrpn_lsb": "1", "nrpn_msb": "60"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 63,
                "min_value": -64,
                "default_value": 0,
            },
            "DEST": {
                "midi": {"cc_msb": "124", "nrpn_lsb": "1", "nrpn_msb": "61"},
                "max_midi_value": 50,
                "min_midi_value": 25,
                "options": [
                    "none",
                    "LFO1: Speed",
                    "LFO1: Multiplier",
                    "LFO1: Fade In/Out",
                    "LFO1: Waveform",
                    "LFO1: Start Phase",
                    "LFO1: Trig Mode",
                    "LFO1: Depth",
                    "LFO2: Speed",
                    "LFO2: Multiplier",
                    "LFO2: Fade In/Out",
                    "LFO2: Waveform",
                    "LFO2: Start Phase",
                    "LFO2: Trig Mode",
                    "LFO2: Depth",
                    "FILTER: Base",
                    "FILTER: Width",
                    "FILTER: Env. Reset",
                    "AMP: Attack Time",
                    "AMP: Hold Time",
                    "AMP: Decay Time",
                    "AMP: Sustain Level",
                    "AMP: Release Time",
                    "AMP: Pan",
                    "AMP: Volume",
                    "FX: Delay Send",
                    "FX: Reverb Send",
                    "FX: Chorus Send",
                    "FX: Bit Reduction",
                    "FX: SRR",
                    "FX: SRR Routing",
                    "FX: Overdrive",
                    "SYN: Data entry knob A, page 1–4",
                    "SYN: Data entry knob B, page 1–4",
                    "SYN: Data entry knob C, page 1–4",
                    "SYN: Data entry knob D, page 1–4",
                    "SYN: Data entry knob E, page 1–4",
                    "SYN: Data entry knob F, page 1–4",
                    "SYN: Data entry knob G, page 1–4",
                    "SYN: Data entry knob H, page 1–4",
                    "SYN: Pitch Bend",
                    "SYN: Aftertouch",
                    "SYN: Mod Wheel",
                    "SYN: Breath Controller",
                    "CC: CC1–16 Values",
                    "FILTER: Attack Time",
                    "FILTER: Decay Time",
                    "FILTER: Sustain Level",
                    "FILTER: Release Time",
                    "FILTER: Frequency",
                    "FILTER: Data entry knob F",
                    "FILTER: Data entry knob G",
                    "FILTER: Envelope Depth",
                    "FILTER: Env. Delay",
                    "FILTER: Key Tracking"
                ],
                "default_value": "none",
            },
            "WAVE": {
                "midi": {"cc_msb": "125", "nrpn_lsb": "1", "nrpn_msb": "62"},
                "max_midi_value": 6,
                "min_midi_value": 0,
                "options": ["tri", "sine", "sqr", "saw", "expo", "ramp", "rand"],
                "default_value": "sine",
            },
            "SPH": {
                "midi": {"cc_msb": "126", "nrpn_lsb": "1", "nrpn_msb": "70"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
            "Trig MODE": {
                "midi": {"cc_msb": "127", "nrpn_lsb": "1", "nrpn_msb": "71"},
                "max_midi_value": 4,
                "min_midi_value": 0,
                "options": ["free", "trig", "hold", "one", "half"],
                "default_value": "free",
            },
            "DEP": {
                "midi": {"cc_msb": "128", "nrpn_lsb": "1", "nrpn_msb": "72"},
                "max_midi_value": 127,
                "min_midi_value": 0,
                "max_value": 127,
                "min_value": 0,
                "default_value": 0,
            },
        },
    },
}


def main():
    print("Hello from elektron-mcp!")


if __name__ == "__main__":
    main()
