elektron_fn_to_midi = {
    "fmdrum": {
        "syn": {
            "syn_type": "FM DRUM",
            "page_1": {
                "tune": {"cc_msb": "40", "nrpn_lsb": "1", "nrpn_msb": "73"},
                "stim": {"cc_msb": "41", "nrpn_lsb": "1", "nrpn_msb": "74"},
                "sdep": {"cc_msb": "42", "nrpn_lsb": "1", "nrpn_msb": "75"},
                "algo": {"cc_msb": "43", "nrpn_lsb": "1", "nrpn_msb": "76"},
                "OP.C": {"cc_msb": "44", "nrpn_lsb": "1", "nrpn_msb": "77"},
                "OP.AB": {"cc_msb": "45", "nrpn_lsb": "1", "nrpn_msb": "78"},
                "FDBK": {"cc_msb": "46", "nrpn_lsb": "1", "nrpn_msb": "79"},
                "FOLD": {"cc_msb": "47", "nrpn_lsb": "1", "nrpn_msb": "80"},
            },
            "page_2": {
                "DEC1": {"cc_msb": "48", "nrpn_lsb": "1", "nrpn_msb": "81"},
                "END1": {"cc_msb": "49", "nrpn_lsb": "1", "nrpn_msb": "82"},
                "RATIO1": {"cc_msb": "50", "nrpn_lsb": "1", "nrpn_msb": "83"},
                "MOD1": {"cc_msb": "51", "nrpn_lsb": "1", "nrpn_msb": "84"},
                "DEC2": {"cc_msb": "52", "nrpn_lsb": "1", "nrpn_msb": "85"},
                "END2": {"cc_msb": "53", "nrpn_lsb": "1", "nrpn_msb": "86"},
                "RATIO2": {"cc_msb": "54", "nrpn_lsb": "1", "nrpn_msb": "87"},
                "MOD2": {"cc_msb": "55", "nrpn_lsb": "1", "nrpn_msb": "88"},
            },
            "page_3": {
                "HOLD": {"cc_msb": "56", "nrpn_lsb": "1", "nrpn_msb": "89"},
                "DEC": {"cc_msb": "57", "nrpn_lsb": "1", "nrpn_msb": "90"},
                "PH.C": {"cc_msb": "58", "nrpn_lsb": "1", "nrpn_msb": "91"},
                "LEV": {"cc_msb": "59", "nrpn_lsb": "1", "nrpn_msb": "92"},
                "NRST": {"cc_msb": "60", "nrpn_lsb": "1", "nrpn_msb": "93"},
                "NRM": {"cc_msb": "61", "nrpn_lsb": "1", "nrpn_msb": "94"},
            },
            "page_4": {
                "NHLD": {"cc_msb": "70", "nrpn_lsb": "1", "nrpn_msb": "97"},
                "NDEC": {"cc_msb": "71", "nrpn_lsb": "1", "nrpn_msb": "98"},
                "TRAN": {"cc_msb": "72", "nrpn_lsb": "1", "nrpn_msb": "99"},
                "TLEV": {"cc_msb": "73", "nrpn_lsb": "1", "nrpn_msb": "100"},
                "BASE": {"cc_msb": "74", "nrpn_lsb": "1", "nrpn_msb": "101"},
                "WDTH": {"cc_msb": "75", "nrpn_lsb": "1", "nrpn_msb": "102"},
                "GRAN": {"cc_msb": "76", "nrpn_lsb": "1", "nrpn_msb": "103"},
                "NLEV": {"cc_msb": "77", "nrpn_lsb": "1", "nrpn_msb": "104"},
            },
        },
        "filter_page": {
            "page_1": {
                "Filter_Type": [
                    "Multi-mode",
                    "Lowpass",
                    "Legacy LP/HP",
                    "Comb-",
                    "Comb+",
                    "Equalizer",
                ],
                "parameters": {
                    "Multi-mode": {
                        "ATK": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
                        "DEC": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
                        "SUS": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
                        "REL": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
                        "FREQ": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
                        "RESO": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
                        "TYPE": {"cc_msb": "18", "nrpn_lsb": "1", "nrpn_msb": "22"},
                        "ENV.Depth": {
                            "cc_msb": "24",
                            "nrpn_lsb": "1",
                            "nrpn_msb": "26",
                        },
                    },
                    "Lowpass": {
                        "ATK": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
                        "DEC": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
                        "SUS": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
                        "REL": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
                        "FREQ": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
                        "RESO": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
                        "ENV.Depth": {
                            "cc_msb": "24",
                            "nrpn_lsb": "1",
                            "nrpn_msb": "26",
                        },
                    },
                    "Legacy LP/HP": {
                        "ATK": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
                        "DEC": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
                        "SUS": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
                        "REL": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
                        "FREQ": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
                        "RESO": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
                        "TYPE(lowpass/highpass)": {
                            "cc_msb": "18",
                            "nrpn_lsb": "1",
                            "nrpn_msb": "22",
                        },
                        "ENV.Depth": {
                            "cc_msb": "24",
                            "nrpn_lsb": "1",
                            "nrpn_msb": "26",
                        },
                    },
                    "Comb-": {
                        "ATK": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
                        "DEC": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
                        "SUS": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
                        "REL": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
                        "FREQ": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
                        "FDBK": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
                        "LPF": {"cc_msb": "18", "nrpn_lsb": "1", "nrpn_msb": "22"},
                        "ENV.Depth": {
                            "cc_msb": "24",
                            "nrpn_lsb": "1",
                            "nrpn_msb": "26",
                        },
                    },
                    "Comb+": {
                        "ATK": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
                        "DEC": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
                        "SUS": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
                        "REL": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
                        "FREQ": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
                        "FDBK": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
                        "LPF": {"cc_msb": "18", "nrpn_lsb": "1", "nrpn_msb": "22"},
                        "ENV.Depth": {
                            "cc_msb": "24",
                            "nrpn_lsb": "1",
                            "nrpn_msb": "26",
                        },
                    },
                    "Equalizer": {
                        "ATK": {"cc_msb": "20", "nrpn_lsb": "1", "nrpn_msb": "16"},
                        "DEC": {"cc_msb": "21", "nrpn_lsb": "1", "nrpn_msb": "17"},
                        "SUS": {"cc_msb": "22", "nrpn_lsb": "1", "nrpn_msb": "18"},
                        "REL": {"cc_msb": "23", "nrpn_lsb": "1", "nrpn_msb": "19"},
                        "FREQ": {"cc_msb": "16", "nrpn_lsb": "1", "nrpn_msb": "20"},
                        "GAIN": {"cc_msb": "17", "nrpn_lsb": "1", "nrpn_msb": "21"},
                        "Q": {"cc_msb": "18", "nrpn_lsb": "1", "nrpn_msb": "22"},
                        "ENV.Depth": {
                            "cc_msb": "24",
                            "nrpn_lsb": "1",
                            "nrpn_msb": "26",
                        },
                    },
                },
            },
            "page_2": {
                "BASE": {"cc_msb": "27", "nrpn_lsb": "1", "nrpn_msb": "24"},
                "WDTH": {"cc_msb": "28", "nrpn_lsb": "1", "nrpn_msb": "25"},
                "ENV.Delay": {"cc_msb": "19", "nrpn_lsb": "1", "nrpn_msb": "23"},
                "KEY.Tracking": {"cc_msb": "26", "nrpn_lsb": "1", "nrpn_msb": "69"},
                "Env.Reset": {"cc_msb": "25", "nrpn_lsb": "1", "nrpn_msb": "68"},
            },
        },
        "amp_page": {
            "ATK": {"cc_msb": "84", "nrpn_lsb": "1", "nrpn_msb": "30"},
            "HOLD": {"cc_msb": "85", "nrpn_lsb": "1", "nrpn_msb": "31"},
            "DEC": {"cc_msb": "86", "nrpn_lsb": "1", "nrpn_msb": "32"},
            "SUS": {"cc_msb": "87", "nrpn_lsb": "1", "nrpn_msb": "33"},
            "REL": {"cc_msb": "88", "nrpn_lsb": "1", "nrpn_msb": "34"},
            "Env. RSET": {"cc_msb": "92", "nrpn_lsb": "1", "nrpn_msb": "41"},
            "MODE": {"cc_msb": "91", "nrpn_lsb": "1", "nrpn_msb": "40"},
            "PAN": {"cc_msb": "89", "nrpn_lsb": "1", "nrpn_msb": "38"},
            "VOL": {"cc_msb": "90", "nrpn_lsb": "1", "nrpn_msb": "39"},
        },
        "fx_page": {
            "BR": {"cc_msb": "78", "nrpn_lsb": "1", "nrpn_msb": "5"},
            "OVER": {"cc_msb": "81", "nrpn_lsb": "1", "nrpn_msb": "8"},
            "SRR": {"cc_msb": "79", "nrpn_lsb": "1", "nrpn_msb": "6"},
            "SR.RT(pre/post)": {"cc_msb": "80", "nrpn_lsb": "1", "nrpn_msb": "7"},
            "OD.RT(pre/post)": {"cc_msb": "82", "nrpn_lsb": "1", "nrpn_msb": "9"},
            "DEL": {"cc_msb": "30", "nrpn_lsb": "1", "nrpn_msb": "36"},
            "REV": {"cc_msb": "31", "nrpn_lsb": "1", "nrpn_msb": "37"},
            "CHR": {"cc_msb": "29", "nrpn_lsb": "1", "nrpn_msb": "35"},
        },
        "lfo": {
            "lfo_1": {
                "SPD": {"cc_msb": "111", "nrpn_lsb": "1", "nrpn_msb": "50"},
                "MULT": {"cc_msb": "111", "nrpn_lsb": "1", "nrpn_msb": "50"},
                "FADE": {},
                "DEST": {},
                "WAVE": {},
                "SPH": {},
                "MODE": {},
                "DEP": {},
            },
            "lfo_2": {
                "SPD": {},
                "MULT": {},
                "FADE": {},
                "DEST": {},
                "WAVE": {},
                "SPH": {},
                "MODE": {},
                "DEP": {},
            },
        },
    },
    "fmtone": {
        "syn": {
            "syn_type": "FM TONE",
            "page_1": {
                "ALGO": "",
                "C": "",
                "A": "",
                "B": ["", ""],
                "HARM": "",
                "DTUN": "",
                "FDBK": "",
                "MIX": "",
            },
            "page_2": {
                "A": {"atk": "", "dec": "", "end": "", "lev": ""},
                "B": {"atk": "", "dec": "", "end": "", "lev": ""},
            },
            "page_3": {
                "ADEL": "",
                "ATRG": "",
                "ARST": "",
                "PHRT": "",
                "BDEL": "",
                "BTRG": "",
                "BRST": "",
            },
            "page_4": {
                "Ratio_Offset": {"C": "", "A": "", "B1": "", "B2": ""},
                "Key_Track": {"A": "", "B1": "", "B2": ""},
            },
        },
        "filter_page": {
            "page_1": {
                "Filter_Type": [
                    "Multi-mode",
                    "Lowpass",
                    "Legacy LP/HP",
                    "Comb-",
                    "Comb+",
                    "Equalizer",
                ],
                "parameters": {
                    "Multi-mode": {
                        "ATK": "",
                        "DEC": "",
                        "SUS": "",
                        "REL": "",
                        "FREQ": "",
                        "RESO": "",
                        "TYPE": "",
                        "ENV": "",
                    },
                    "Lowpass": {
                        "ATK": "",
                        "DEC": "",
                        "SUS": "",
                        "REL": "",
                        "FREQ": "",
                        "RESO": "",
                        "ENV": "",
                    },
                    "Legacy LP/HP": {
                        "ATK": "",
                        "DEC": "",
                        "SUS": "",
                        "REL": "",
                        "FREQ": "",
                        "RESO": "",
                        "TYPE": ["Lowpass", "Highpass"],
                        "ENV": "",
                    },
                    "Comb-": {
                        "ATK": "",
                        "DEC": "",
                        "SUS": "",
                        "REL": "",
                        "FREQ": "",
                        "FDBK": "",
                        "LPF": "",
                        "ENV": "",
                    },
                    "Comb+": {
                        "ATK": "",
                        "DEC": "",
                        "SUS": "",
                        "REL": "",
                        "FREQ": "",
                        "FDBK": "",
                        "LPF": "",
                        "ENV": "",
                    },
                    "Equalizer": {
                        "ATK": "",
                        "DEC": "",
                        "SUS": "",
                        "REL": "",
                        "FREQ": "",
                        "GAIN": "",
                        "Q": "",
                        "ENV": "",
                    },
                },
            },
            "page_2": {
                "BASE": "",
                "WDTH": "",
                "ENV.D": "",
                "KEY.T": "",
                "BW.RT": ["Pre", "Post"],
                "F.RST": "",
            },
        },
        "amp_page": {
            "ATK": "",
            "DEC": "",
            "SUS": "",
            "REL": "",
            "RSET": "",
            "MODE": "",
            "PAN": "",
            "VOL": "",
        },
        "fx_page": {
            "BR": "",
            "OVER": "",
            "SRR": "",
            "SR.RT": ["Pre", "Post"],
            "DEL": "",
            "REV": "",
            "CHR": "",
            "OD.RT": ["Pre", "Post"],
        },
        "lfo": {
            "lfo_1": {
                "SPD": "",
                "MULT": "",
                "FADE": "",
                "DEST": "",
                "WAVE": "",
                "SPH": "",
                "MODE": "",
                "DEP": "",
            },
            "lfo_2": {
                "SPD": "",
                "MULT": "",
                "FADE": "",
                "DEST": "",
                "WAVE": "",
                "SPH": "",
                "MODE": "",
                "DEP": "",
            },
            "lfo_3": {
                "SPD": "",
                "MULT": "",
                "FADE": "",
                "DEST": "",
                "WAVE": "",
                "SPH": "",
                "MODE": "",
                "DEP": "",
            },
        },
    },
    "swarmer": {
        "syn": {
            "syn_type": "SWARMER",
            "page_1": {
                "TUNE": "",
                "SWRM": "",
                "DET": "",
                "MIX": "",
                "M.OCT": "",
                "MAIN": "",
                "ANIM": "",
                "N.MOD": "",
            },
        },
    },
    "wavetone": {
        "syn": {
            "syn_type": "WAVETONE",
            "page_1": {
                "TUN1": "",
                "WAV1": "",
                "PD1": "",
                "LEV1": "",
                "TUN2": "",
                "WAV2": "",
                "PD2": "",
                "LEV2": "",
            },
            "page_2": {
                "OFS1": "",
                "TBL1": "",
                "MOD": "",
                "RSET": "",
                "OFS2": "",
                "TBL2": "",
                "DRIF": "",
            },
            "page_3": {
                "ATK": "",
                "HOLD": "",
                "DEC": "",
                "NLEV": "",
                "BASE": "",
                "WDTH": "",
                "TYPE": "",
                "CHAR": "",
            },
        },
    },
}


def main():
    print("Hello from elektron-mcp!")


if __name__ == "__main__":
    main()
